<?php

//
// Configuraion file
//

set_time_limit(600); //set timeout to 10 minutes, or you can set max_execution_time in php.ini

$config['accountname'] = 'yoichikademo3';
$config['accountkey'] = 'gZJkBXsIhWKHQ6jQfRcdHaNuWHnGdkXlTdGhOzPymBA=';
$config['issuer'] = 'https://yoichika.accesscontrol.windows.net';
$config['audience'] = 'urn:contoso';

//$config['accountname'] = 'yoichitest';
//$config['accountkey'] = '7wgx+hMgxxt2MLMpjxPvS1o267biw/Sg5PiTa/yVH6A=';
//$config['issuer'] = 'https://contoso.accesscontrol.windows.net';
//$config['audience'] = 'urn:contoso';

?>
